### ISSUE TITLE
Implementar validador em python

### ISSUE THREAD

**Issue by cleogarcia** [UFAM-ICOMP-WACAD/intro-github-flow-gitexec#6]

**Comment by eduardonoji** [comment]
3. (Desenvolvedor) Crie a(s) _branch(es)_ para execução das tarefas
    - Instancie localmente a(s) __branch(es)__;
   
![1](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/a23296f9-738d-4ece-8d1a-8654b15d1961)
    - Implemente as soluções nos arquivos _validador.js_ e _validador.py_
    
![2](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/5959466e-8f8b-4cab-8709-401fa97f403e)
      - Cada desenvolvedor deve alterar parcialmente um dos arquivos (.py ou .js) e completamente o outro. 
    -  Apresente imagens que comprove a operação.
    
![11](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/3ae31933-87ee-420b-8341-fd44b7c7c582)

![12](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/56816687-b586-4b7e-92be-a33645ad8141)

4. (Desenvolvedor) Faça o _push_ dos commits para a(s) _branch(es)_ criadas e abra uma _pull request_
    - Na descrição da _pull request_, informe a issue que está sendo fechada usando #
    - Apresente imagens que comprove a operação.
    
![5](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/55c23698-58f9-4391-8556-b43ae7d9fd64)

![6](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/419636b2-6c6d-4459-8c29-19639381fd67)

![7](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/4d485844-ce29-4b14-8772-2a248300eaef)

![8](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/07c6f400-e49c-45d1-a916-84194d01cbd7)

6. (Desenvolvedor) Faça o _merge_ da _pull request_ com o _branch master_     
    - Resolva os conflitos considerando o código que você criou;
    - Apresente imagens que comprove a operação.
  
![9](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/22826892-52eb-4575-8670-8f568c3c842f)

7. (Desenvolvedor) Atualize a branch principal no seu computador;
    - Apresente images que comprove a operação.

![10](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/02586559-8648-4eb7-9676-246cb5dd7b84)

8. (Desenvolvedor) Remova a(s) _branch(es)_ criadas tanto localmente quanto no github.
    - Apresente imagens que comprove a operação.
    - Local:
![13](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/76576f37-a540-4517-af1a-2a0c3d4b5e2a)

    - GitHub:
    
![14](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/a85f4f3f-98f9-493c-b8de-626b129426fe)
![15](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/86121189/e92eda05-9c0c-42c0-806b-4ee13a26505b)
