### ISSUE TITLE
Implementar documentação validador em javaScript.

### ISSUE THREAD

**Issue by cleogarcia** [UFAM-ICOMP-WACAD/intro-github-flow-gitexec#7]
(Desenvolvedor0 Crie a(s) __branch(es)__ para execução das tarefas
![primeiro commit](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276460/fb9bb513-fa3f-455f-90e3-e069b36a42c1)

Criando a branch
![inserido alteração no código e realizado segundo commit](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276460/cfd75a8c-8444-4036-9723-e246e9c138c4)

Instanciando e dando push
![arquivo acrescentado validador java e arquivo modificado validador js agora foi enviado](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276460/20f880f0-bffd-4a1e-a67d-da0ef43ad267)

Operações realizadas
![branchcriado](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276460/66ef8ae4-e187-4002-819f-0f1b326dd667)

**Comment by cdanielribeiro** [comment]
(Desenvolvedor) Crie a(s) _branch(es)_ para execução das tarefas
    - Instancie localmente a(s) _branch(es)_;
git fetch origin
git checkout 7-implementar-documentação-validador-em-javascript

![Imagem01](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276662/2c5187bc-07b8-40dd-8278-d8e155136de5)

    
    - Implemente as soluções nos arquivos _validador.js_ e _validador.py_
    - Cada desenvolvedor deve alterar parcialmente um dos arquivos (.py ou .js) e completamente o outro. 
    - Apresente imagens que comprove a operação.
![Imagem02](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276662/7cf5e2ac-93e5-4d68-9f06-fcb99ae09399)

Faça o _push_ dos commits para a(s) _branch(es)_ criadas e abra uma _pull request_
    - Na descrição da _pull request_, informe a issue que está sendo fechada usando #
    - Apresente imagens que comprove a operação.
  
![Imagem03](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276662/7d24204b-b958-41c0-b02d-d51c28c21a66)

**Comment by cdanielribeiro** [comment]
6. (Desenvolvedor) Faça o _merge_ da _pull request_ com o _branch master_     
    - Resolva os conflitos considerando o código que você criou;
    - Apresente imagens que comprove a operação
    
![Imagem04](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276662/87819020-ea3b-4b01-9b72-5ff9a2221090)


7. (Desenvolvedor) Atualize a branch principal no seu computador;
    - Apresente images que comprove a operação
  
![Imagem05](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/142276662/0b681554-9ed6-4684-9846-9014abd5e2e8)

**Comment by cleogarcia** [comment]
![Trabalho Final git img-0002](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/11917378/b8070650-81d2-46d9-a698-fb2ebbd7cd07)
![Trabalho Final git img-0003](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/11917378/17ccae16-25eb-40b9-b935-084224a74207)
![Trabalho Final git img-0004](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/11917378/9749ba0a-0a81-461e-8bac-a5a7689d4f5b)
![Trabalho Final git img-0005](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/11917378/eed0bbe7-6060-4471-93f2-ff96e803cd30)
![Trabalho Final git im-0001](https://github.com/UFAM-ICOMP-WACAD/intro-github-flow-gitexec/assets/11917378/e184dff8-21ff-4800-8f0c-81a56029605f)
